title: D Language Blog Archive
description: The official blog for the D Programming Language.

url: "https://blog.dlang.org"
baseurl: ""

# Set a custom URL depending on what folder the file is in
defaults:
  - scope:
      path: "_posts/live"
    values:
      layout: post
      permalink: /:year/:month/:day/:title/

  - scope:
      path: "_posts/archive"
    values:
      layout: post
      permalink: /archive/:year/:month/:day/:title/

# Tell Jekyll to ignore files in this folder
exclude:
  - prepub

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 10
paginate_path: "/page/:num/"

feed:
  path: "/feed.xml"
